# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6220182e47a23dcb7bb7477ae81e2ef058abb66d12e342116ce6a5b114343fd8c07ade25b40f48619a4b88f53ace7a75ba8cc9af36c5eb333a59aad33cc0e0a7

test:
  secret_key_base: b9e2ebe4f28ffccd99d226adc3f57945c8159692443843a4dacd016432c8abd16f440c53d2f1bc7e20afea724d7a5db6997498039ddf81171c8229bbf4dd3bfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
